data_ingestion:
  resize_shape: [512, 512]

image_captioning:
  max_new_tokens: 64   # Adjust based on your desired caption length
  task_prompt: "<MORE_DETAILED_CAPTION>"
  num_beams: 3

story_generation:
  max_tokens: 700
  temperature: 0.7
  top_p: 0.9
  story_prompt_template: |
    Expand the following image description into a {theme} story of around 
    {word_limit} words (strictly not exceeding the word limit). Be creative, engaging, and vivid.

    Image Description: {caption}

    Story: