


data_ingestion:
  raw_data_dir: "data/raw"
  ingested_data_dir: "data/ingested"
  allowed_extensions: ["jpg", "jpeg", "png"]
  max_file_size: 5242880  # 5MB

image_captioning:
  ingested_data_dir: "data/ingested"
  captions_dir: "data/captions"
  florence2_model_name: "microsoft/Florence-2-large-ft"
  florence2_model_revision: "v1.0"
  florence2_processor_revision: "v1.0"
  
story_generation:
  captions_dir: "data/captions"
  stories_dir: "data/stories"
  model_name: "meta-llama/Llama-3.3-70B-Instruct-Turbo-Free"
  together_api_key: "${TOGETHER_API_KEY}"  # Set via environment variable or .env
